### ISSUE TITLE
Extensions web page should link to authoring

### ISSUE THREAD

**Issue by nmcl** [quarkusio/extensions#1007]
The extensions web page which lists those available (https://quarkus.io/extensions/) should link to the authoring extensions page(s) such as https://quarkus.io/guides/extension-authors-guide as potential authors may come to that page first via a google search and then not know how to get to the author page directly.

Not sure how best to add that though. It's not a category down the left hand side, I think.

**Comment by holly-cummins** [comment]
Is something odd with the edits or timestamps on this? https://quarkus.io/extensions/ definitely wasn't available in 2019. :) 

<img width="446" alt="image" src="https://github.com/quarkusio/extensions/assets/11509290/f37972fa-d96d-4912-9354-b679ea5a9316">

One partial resolution of this is that we link to the related content in the menu headers: 

<img width="1080" alt="image" src="https://github.com/quarkusio/extensions/assets/11509290/5e3e2747-7786-4a90-942b-76881c6e4a36">

... but I agree that we could also do more. 

There's probably two categories of help we might want to call out:
- Want to write your own extension?
- Want your extension to be listed here?

One of those could go into the footer, but probably not two - and with the current scrolling system, the footer is only really visible on the extension details pages.

**Comment by holly-cummins** [comment]
Ahh, mystery solved with the help of the wayback machine:

<img width="2003" alt="image" src="https://github.com/quarkusio/extensions/assets/11509290/2eb0b4f6-efcf-437e-8544-9013a3d052b4">

That page listing all the extensions had disappeared off http://quarkus.io by the time I joined the team - it lived on as http://quarkus.pro/extensions/, but I hadn't realised that the cloner site was showing content which had once existed on http://quarkus.io.

**Comment by holly-cummins** [comment]
Closing this, since we figured out the story of it, and the links are now added.
