### ISSUE TITLE
Amazon Services from Quarkiverse is not shown (but we have the old Core extensions)

### ISSUE THREAD

**Issue by gsmet** [quarkusio/extensions#102]
See title ^.

![extensions-amazon-services](https://user-images.githubusercontent.com/1279749/216973068-7c73ec11-2360-4991-93bb-a78e111401b1.png)

**Comment by aloubyansky** [comment]
These extensions used to be in the core repo originally but were relocated to Quarkiverse. It was decided to still keep the old groupId and relocation in core though. I think we could drop relocations in 3.x.

**Comment by gastaldi** [comment]
+1 to drop relocations /cc @gsmet

**Comment by gsmet** [comment]
@aloubyansky @gastaldi I don't see how what you're saying explains why Holly can't find the extensions?

**Comment by gsmet** [comment]
No, I don't think so.
I think we should have the Quarkiverse ones around.

@aloubyansky but the relocations are considered extensions themselves? AFAICS, it points to the 2.5.4.Final version so not the version of the relocations.

**Comment by aloubyansky** [comment]
Ah, ok, I see. It's the same reason we don't have CEQ and other extensions. Amazon is a platform member on its own and not included in the core quarkus-bom, only the relocations are.

**Comment by holly-cummins** [comment]
@gsmet, I think this is fixed now. The combination of https://github.com/quarkusio/registry.quarkus.io/pull/92 and #73 has sorted it out (I hope!). For example, for Amazon DynamoDb, I now don't see the extension you've circled, and I do see others with a different version:

<img width="1780" alt="image" src="https://user-images.githubusercontent.com/11509290/223166773-506051a2-db9c-4ac6-aba2-f3dab2c04c42.png">

Looking at [one of the dynamo db extensions from that front page](https://quarkus.io/extensions/io.quarkiverse.amazonservices/quarkus-amazon-dynamodb), it's quite recently released, and in the Amazon platform: 

<img width="426" alt="image" src="https://user-images.githubusercontent.com/11509290/223167737-5237e665-20d2-4f61-97e2-923a49aa2dc0.png">

At the bottom it links back to the older DynamoDb extension:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/11509290/223167978-ba93aac6-a06e-4536-9b35-c13f104f9a07.png">

Closing this, but @gsmet please re-open if you think it's still not right.
