### ISSUE TITLE
Categories in the left column are randomly ordered?

### ISSUE THREAD

**Issue by gsmet** [quarkusio/extensions#104]
I don't think an alphabetical order makes sense but IIRC they used to be ordered on the guides index of the website and the current order in the left column looks very random.

Could we maybe put the infrastructure in place to have a better ordering?

**Comment by holly-cummins** [comment]
Yes, that makes sense. I think at the moment they probably are randomly ordered. :) Alphabetical would be trivial to do, so we could do that while we think of a better option.

Hardcoding an order to match what Guides does  creates a question about how we handle 'new' categories defined by an extension, like 'testing'. A reasonable solution would be to hardcode and then have unknown ones at the bottom. Or, what could be nice is to order by popularity, either number of occurrences in the extensions, or perhaps number of overall downloads of that category.
