### ISSUE TITLE
Extension logos are clipped 

### ISSUE THREAD

**Issue by emilienbev** [quarkusio/extensions#1186]
On their single view pages, some extensions have their logos clipped on the right hand side. 
Some examples: 
- [Couchbase](https://quarkus.io/extensions/io.quarkiverse.couchbase/quarkus-couchbase/)
- [Quinoa](https://quarkus.io/extensions/io.quarkiverse.quinoa/quarkus-quinoa/)
- [Temporal](https://quarkus.io/extensions/io.quarkiverse.temporal/quarkus-temporal/)

It looks like the image/svg gets resized to 220x220px, but the parent div cuts the right handside. It's not a huge deal but I thought of letting you know.

**Comment by holly-cummins** [comment]
Thanks for the report!
