### ISSUE TITLE
built with has no "All" option

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/extensions#199]
can't seem to go back to "All" when have picked a version. (at least not without reloading the page)

**Comment by holly-cummins** [comment]
Yeah. it's annoying. Workaround-able by reload, but very annoying. I think this is a duplicate of [#39.](https://github.com/quarkusio/extensions/issues/39), do you agree?

(See also https://github.com/quarkusio/extensions/pull/200, which fixes this.)

**Comment by maxandersen** [comment]
yes  - duplicate.
