### ISSUE TITLE
Improve extension-details page on mobile

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/extensions#392]
... but we can make it work with 2 css changes on a media call.

Now: 

![image](https://github.com/quarkusio/extensions/assets/11509290/936efe73-2e25-437b-84e2-b7e46fd07d43)

Proposed: 

![image](https://github.com/quarkusio/extensions/assets/11509290/238588d9-2043-4bbc-bfca-18615572009e)

**Comment by insectengine** [comment]
In this class, add a media call to switch from row to column to make the two rows stack:

`.jGsGyi {
@media screen and (max-width: 768px) { 
flex-direction: column; 
}
}`

The left column will now be on top, but it's narrow and we want to make it full width so you'll need another media call:

`.jXTyRz {
   @media screen and (max-width: 768px) { 
width:100%
}
}`

While we're at it... on the smaller size, let's remove the padding on the left side of the original right column and add a litt:

`.kUuyMP {
@media screen and (max-width: 768px) { 
padding-left: 0px;
padding-top: 2rem;}
}`

**Comment by holly-cummins** [comment]
The contributor graphs have a hardcoded width (because I ran out of energy), so also very much need a @media query to make them render sensibly on small screens.
