### ISSUE TITLE
Undesirable blue ring on filter text input, when selected

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/extensions#98]
A blue ring appears on the text input for the filter, when it's being used: 

![image](https://user-images.githubusercontent.com/11509290/216572204-186880b3-5b36-4ce3-a7e3-2f656e065f93.png)

In contrast, on the main site, there's only subtle decoration when the filter input is selected:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/11509290/216572388-6dc34d06-e112-404b-a2f7-6a57af2eba89.png">

(There is still a dark blue box, but it's around the whole edge of the white area, so it's more subtle.)

... so the blue ring is a bit strange no matter what, and it's not consistent with the main site.

**Comment by gsmet** [comment]
@holly-cummins I just noticed that too and it's annoying.

I added:
```
input:focus-visible {
    outline: none;
}
```
locally and AFAICS it's gone (on Firefox at least). I think you need to add a specific class to the button (there is one but it looks randomly generated so I'm not sure we can actually rely on the name).

Could you test if it also fixes the problem for you?

**Comment by holly-cummins** [comment]
Thanks for the pointer, @gsmet, that's saved me a lot of time! The reason the class names look random is because they're generated by [Styled Components](https://styled-components.com/). I've removed the outline on the input element and moved so that the whole search box gets a focus outline, which is what happens on the main http://quarkus.io site. It doesn't look exactly like it does on the main site, just because the background colour is different. We may end up redoing the filtering to have a blue background as part of giving the site a more mobile-friendly design (#5), so we can revisit the border colour and thickness then.
